# JVM memory allocation, UTF-8 encoding, and Windows cache stability
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Dsun.io.useCanonCaches=false -Dsun.io.useCanonPrefixCache=false

# Performance & Caching Optimizations
org.gradle.caching=true
org.gradle.parallel=true

# AndroidX Migration & R Class Namespacing
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin Code Style
kotlin.code.style=official

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
